---
name: Sample AWS web service
docPath: docs/arch
views:
  -
    name: overview
    layers: ["aws"]
nodes:
  -
    name: cdn
    components:
      - CloudFront?icon=aws-cloud-front
      - Waf?icon=aws-waf
    clusters:
      - "aws:account1?icon=aws-virtual-private-cloud"
  -
    name: frontend
    components:
      - Beanstalk?icon=aws-elastic-beanstalk
    clusters:
      - "aws:account2?icon=aws-virtual-private-cloud"
  -
    name: api
    components:
      - ECS?icon=aws-elastic-container-service
    clusters:
      - "aws:account3?icon=aws-virtual-private-cloud"
  -
    name: db
    components:
      - AuroraMySQL?icon=aws-aurora 
    clusters:
      - "aws:account3?icon=aws-virtual-private-cloud"
  -
    name: dynamodb
    components:
      - DynamoDB?icon=aws-dynamo-db
    clusters:
      - "aws:account3?icon=aws-virtual-private-cloud"
networks:
  -
    route:
      - "internet"
      - "cdn:CloudFront"
  -
    route:
      - "cdn:CloudFront"
      - "frontend:Beanstalk"
  -
    route:
      - "frontend:Beanstalk"
      - "api:ECS"
  -
    route:
      - "api:ECS"
      - "dynamodb:DynamoDB"
  -
    route:
      - "api:ECS"
      - "db:AuroraMySQL"
  -
    route:
      - "api:ECS"
      - "Payment API"
relations:
  -
    components:
      - "cdn:CloudFront"
      - "cdn:Waf"